name: "Test"

on:
  push:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"
  workflow_dispatch:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        scope: ${{ fromJSON( inputs.test_input | jq -R 'split(",")' ) }}
    name: "${{ matrix.scope }}"
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.scope }}
