name: "Test"

on:
  push:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"
  workflow_dispatch:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"

jobs:
  split-input:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "scopes=`echo ${{ inputs.test_input }} | jq -R 'split(",")'`" >> "$GITHUB_OUTPUT"
  test-job:
    needs: split-input
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        scope: ${{ fromJSON( needs.split-input.outputs.scopes ) }}
    name: "${{ matrix.scope }}"
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.scope }}
