name: "Test"

on:
  push: {}
  workflow_dispatch:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"

jobs:
  split-input:
    runs-on: ubuntu-latest
    steps:
      - id: split
        shell: bash
        run: |
          TEST_INPUT=${{ inputs.test_input }}
          TEST_INPUT=${TEST_INPUT:-"abc,def,ghi"}
          echo "scopes=`echo ${TEST_INPUT} | jq -Rc 'split(",")'`" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
    outputs:
      scopes: ${{ steps.split.ouputs.scopes }}
  test-job:
    needs: split-input
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        scope: ${{ needs.split-input.outputs.scopes }}
    name: "${{ matrix.scope }}"
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.scope }}
