name: "Test"

on:
  push: {}
  workflow_dispatch:
    inputs:
      data_products:
        description: "blah"
        required: false
        default: ""

jobs:
  split-input:
    runs-on: ubuntu-latest
    steps:
      - id: split
        shell: bash
        run: |
          DATA_PRODUCTS=${{ inputs.data_products }}
          DATA_PRODUCTS=${DATA_PRODUCTS:-"activity,calories,cardio,sleep,workout"}
          echo "data_products=`echo ${DATA_PRODUCTS} | jq -Rc 'split(",")'`" >> $GITHUB_OUTPUT
    outputs:
      data-products: ${{ steps.split.outputs.data_products }}
  test-job:
    needs: split-input
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        data-product: ${{ fromJSON(needs.split-input.outputs.data-products) }}
    name: "${{ matrix.data-product }}"
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.data-product }}
