name: "Test"

on:
  push: {}
  workflow_dispatch:
    inputs:
      test_input:
        description: "blah"
        required: true
        default: "abc,def,ghi"

jobs:
  split-input:
    runs-on: ubuntu-latest
    steps:
      - id: split
        shell: bash
        run: |
          genv=`cat $GITHUB_ENV`
          echo $genv
    outputs:
      scopes: ${{ steps.split.outputs.scopes }}
  test-job:
    needs: split-input
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        scope: ${{ fromJSON(needs.split-input.outputs.scopes) }}
    name: "${{ matrix.scope }}"
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.scope }}
