name: "Test"

on:
  push: {}
  workflow_dispatch:
    inputs:
      test_input:
        description: "blah"
        required: false
        default: ""

jobs:
  split-input:
    runs-on: ubuntu-latest
    steps:
      - id: split
        shell: bash
        run: |
          TEST=${{ inputs.test_input:-"abc,def,ghi" }}
          echo $TEST